language: python
python:
  - "2.7"
virtualenv:
    system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install git build-essential gfortran python-dev liblapack-dev python-openbabel python-setuptools python-pip
  # for database testing, we don't need the inchi libraries, so no need to build rdkit from source
  - sudo apt-get install python-rdkit librdkit-dev librdkit1 rdkit-data
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
  - cd ..
  # this is the RMG-database project, so need to fetch RMG-Py
  - git clone https://github.com/GreenGroup/RMG-Py.git
  - git clone https://github.com/GreenGroup/PyDAS.git
  - git clone https://github.com/GreenGroup/PyDQED.git
install:
  - cd $TRAVIS_BUILD_DIR
  - cd ..
  - cd RMG-Py
  - pip install numpy
  - pip install -r requirements.txt
  - cd ..
  - cd PyDAS
  - make F77=gfortran
  - make install
  - cd ..
  - cd PyDQED
  - make F77=gfortran
  - make install
  - cd ..
  - cd RMG-Py
  - make noQM -j2
script:
  - nosetests -v -d --nologcapture $TRAVIS_BUILD_DIR/../RMG-Py/databaseTest.py
